tweaks:
  welcome:
    enabled: false
    message: "Welcome to the server!"
  enchant-disabler:
    enabled: true
    # Get material names from here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    items:
      - "ELYTRA"
#      - "MACE"
  animal-swim:
    enabled: true
    swim-assist-velocity: 0.15
    # List of entity types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    entities:
      - "HORSE"
