tweaks:
  welcome:
    enabled: false
    message: "Welcome to the server!"
  enchant-disabler:
    enabled: true
    # Get material names from here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    items:
      - "ELYTRA"
#      - "MACE"
