name: VTweaks
version: '0.3.0'
main: gg.valentinos.alexjoo.VTweaks
api-version: '1.21'
authors: [ Alex_Joo, git4rker ]
description: VTweaks, short for Valentinos Tweaks, is a plugin that adds various tweaks to the server.
website: valentinos.gg
commands:
  welcome:
    # tweaks.welcome permission to use this command
    # tweaks.welcome.set permission to set the welcome message
    description: Sends a welcome message to the player. /welcome set <message> to set a new one.
    usage: command is currently disabled
    aliases: [ w ]