name: ValentinosTweaks
version: '0.2.0'
main: gg.valentinos.alexjoo.ValentinosTweaks
api-version: '1.21'
authors: [ Alex_Joo ]
description: ValentinosTweaks, short for Valentinos Tweaks, is a plugin that adds various tweaks to the server.
website: valentinos.gg
commands:
  welcome:
    # tweaks.welcome permission to use this command
    # tweaks.welcome.set permission to set the welcome message
    description: Sends a welcome message to the player. /welcome set <message> to set a new one.
    usage: command is currently disabled
    aliases: [ w ]